# Site settings
title: MacxApps
email: pingjiang1989@gmail.com
description: "Open source replacement of official macx.cn client."
baseurl: ""
url: "http://pingjiang.github.io/MacxApps"
github: "https://github.com/pingjiang/MacxApps"
author: "pingjiang"

# Build settings
markdown: kramdown
permalink: pretty
